### ISSUE TITLE
Reboot handling

### ISSUE THREAD

**Issue by tobru** [rancher/system-upgrade-controller#23]
**Is your feature request related to a problem? Please describe.**

In the current implementation the state of the upgrade process is determined by the Job status. If the Job is successful, the process is considered done and the node gets uncordoned. However if the Job is unsuccessful, no uncordoning happens. If the upgrade process f.e. just issues a `reboot` during it's work, the Job is most likely failing as the node gets suddenly rebooted and as such never gets uncordoned.

Also if you defer rebooting f.e. by using `shutdown -r [TIME]`, it gets worse as the node is uncordoned and later rebooted without another proper draining.

**Describe the solution you'd like**

One solution to this issue could be to implement the reboot logic into SUC as a toplevel configuration in the Plan, like `spec.reboot: true` and issue a reboot when the Job is considered successful. Then track the reboot process and uncordon only when the node is properly back from reboot. This is something which is perfectly working in [Kured](https://github.com/weaveworks/kured), so probably cheating a bit there to implement a similar way could be a good way to start.

**Describe alternatives you've considered**

An alternative could be to combine SUC and Kured, but this would lead into draining the node two times, once by SUC and once by Kured which is considered suboptimal.

**Comment by dweomer** [comment]
@tobru I have tested this on k3OS incurring a reboot and uncordon has worked for me every time.

Additionally, I have a backoff limit for the jobs that are created set to 2 so as to allow for the process to execute again and only reboot if something changed. This allows for the case where a job runs and someone incurs a failure during the first run because of a reboot but should run to completion the second time without issue. This only works of course if the upgrade job only reboots if it has actually made a change. I think your upgrade script that you shared in #19 should work as-is. Is such not the case?

**Comment by tobru** [comment]
I gave it another try, this is how I tested:

1. created a new node which needs updates incl. reboot
2. made sure the plan gets executed
3. the node got rebooted, but the job doesn't end

This is how the Pod status looks like after the reboot:

```
# kubectl get po
NAME                                                              READY   STATUS    RESTARTS   AGE
system-upgrade-controller-55cc699586-wxhwf                        1/1     Running   0          6m29s
upgrade-node-6-with-ubuntu-latest-at-c1fd4666ae0c7dfb25eb-j8t62   0/1     Unknown   0          6m2s
upgrade-node-6-with-ubuntu-latest-at-c1fd4666ae0c7dfb25eb-6xbgz   0/1     Error     0          2m44s
```

* `upgrade-node-6-with-ubuntu-latest-at-c1fd4666ae0c7dfb25eb-j8t62` was the Pod with the reboot in it
* `upgrade-node-6-with-ubuntu-latest-at-c1fd4666ae0c7dfb25eb-6xbgz` is the Pod started after the reboot

The issue is that the second time the script runs and no reboot is needed, the exit code isn't `0` and therefore the Pod considered failed. I need to investigate further how to have a proper update handling script, will report back here.

Nevertheless: In this case, even if the script would end with exit code `0`, the first Pod which issued the reboot is left in `Unknown` status which isn't that nice. I'm not sure how to solve this, other than doing the reboot in a more controlled way like kured does. What do you think?

**Comment by tobru** [comment]
With this snippet it does work:

```
    args:
      - sh
      - -c
      - |
        export DEBIAN_FRONTEND=noninteractive && \
        apt-get -q update && \
        apt-get -qy dist-upgrade --auto-remove --purge && \
        [ -f /var/run/reboot-required ] && reboot || exit 0
```

**Comment by dweomer** [comment]
> ```
> # kubectl get po
> NAME                                                              READY   STATUS    RESTARTS   AGE
> system-upgrade-controller-55cc699586-wxhwf                        1/1     Running   0          6m29s
> upgrade-node-6-with-ubuntu-latest-at-c1fd4666ae0c7dfb25eb-j8t62   0/1     Unknown   0          6m2s
> upgrade-node-6-with-ubuntu-latest-at-c1fd4666ae0c7dfb25eb-6xbgz   0/1     Error     0          2m44s
> ```
> 
> * `upgrade-node-6-with-ubuntu-latest-at-c1fd4666ae0c7dfb25eb-j8t62` was the Pod with the reboot in it
> * `upgrade-node-6-with-ubuntu-latest-at-c1fd4666ae0c7dfb25eb-6xbgz` is the Pod started after the reboot
> 
> The issue is that the second time the script runs and no reboot is needed, the exit code isn't `0` and therefore the Pod considered failed. I need to investigate further how to have a proper update handling script, will report back here.

This is exactly the issue: when the process is re-run and has nothing to do it should exit successfully. This is the underlying assumption that this controller was built with: re-application of an upgrade will result in the same end-state (idempotency) AND such will exit successfully.

> Nevertheless: In this case, even if the script would end with exit code `0`, the first Pod which issued the reboot is left in `Unknown` status which isn't that nice. I'm not sure how to solve this, other than doing the reboot in a more controlled way like kured does. What do you think?

The `Unknown` state due to reboot mid-job is unsightly but a natural result of the operation. k3OS side-steps this by doing `nsenter -a -t 1 -- reboot` which returns immediately and effects a runlevel change in the background. Maybe pairing this controller with another controller such as kured is a path forward?

**Comment by tobru** [comment]
> This is exactly the issue: when the process is re-run and has nothing to do it should exit successfully. This is the underlying assumption that this controller was built with: re-application of an upgrade will result in the same end-state (idempotency) AND such will exit successfully.

Understood, makes sense!

> k3OS side-steps this by doing nsenter -a -t 1 -- reboot which returns immediately and effects a runlevel change in the background.

I tried that in the above snippet instead of `reboot` and of course this command has the same effect: the node gets rebooted. But still, the Pod has the `Unknown` status after the node is back from reboot. Does the Pod properly terminate in the k3OS case?

> Maybe pairing this controller with another controller such as kured is a path forward?

I gave this another thought: kured relies on the behavior of the package manager or upgrade procedure to somewhere place a file which triggers the reboot. Not all package managers or upgrade procedures do that, so one would have to place the file there in the upgrade script. And nevertheless, some sort of coordination would be needed between the two controllers so that f.e. not two or more drains are needed and they don't interfere on each other. Now that I understand the idea behind the way how SUC works with the Job status, I would suggest to keep this concept for the time being. If using the controller in production for some time shows that there needs to be improvements to the reboot procedure, this can be discussed again at a later time again.

**Comment by dweomer** [comment]
> > k3OS side-steps this by doing nsenter -a -t 1 -- reboot which returns immediately and effects a runlevel change in the background.
> 
> I tried that in the above snippet instead of `reboot` and of course this command has the same effect: the node gets rebooted. But still, the Pod has the `Unknown` status after the node is back from reboot. Does the Pod properly terminate in the k3OS case?

Yes but this is because it is invoking OpenRC's reboot (instead of just invoking the syscall) which changes the run-level to `shutdown` thus incurring the reboot activities in the background. It's a race but so far the k3OS upgrade job is winning.

> > Maybe pairing this controller with another controller such as kured is a path forward?
> 
> I gave this another thought: kured relies on the behavior of the package manager or upgrade procedure to somewhere place a file which triggers the reboot. Not all package managers or upgrade procedures do that, so one would have to place the file there in the upgrade script. And nevertheless, some sort of coordination would be needed between the two controllers so that f.e. not two or more drains are needed and they don't interfere on each other. Now that I understand the idea behind the way how SUC works with the Job status, I would suggest to keep this concept for the time being. If using the controller in production for some time shows that there needs to be improvements to the reboot procedure, this can be discussed again at a later time again.

Yes, another thing that the k3OS upgrade does is attempt to establish an `flock()` early on the standard location in the host filesystem (see https://github.com/rancher/k3os/blob/v0.9.0-rc5/pkg/cli/upgrade/upgrade.go#L128-L131). Different upgrade systems solve this in different ways which is why I left as an exercise for the upgrade packager/definer to get right. You'll notice that for apt/deb based systems (provided you've chroot'd into the /host filesystem) a similar lock is attempted already which will fail if another process is attempting to upgrade.

That said, there is some upgrade pod anti-affinity baked in such that no two jobs/pods for the same plan will apply at the same time on the same host: https://github.com/rancher/system-upgrade-controller/blob/64e51c9fa56edacb86958a3446189608519dcb41/pkg/upgrade/job/job.go#L122-L135

**Comment by tobru** [comment]
Thanks @dweomer for the explanation. With that, I intend to close this issue and treat it as resolved. If you feel like keeping it open, let me know. Otherwise I'll close it tomorrow.

**Comment by newbenji** [comment]
I know its closed, but actually think a spec.reboot: true would be a nice thing
Maybe even with a possible condition. So an upgrade of kubernetes can easy be done while upgrading the os behind.

**Comment by jzandbergen** [comment]
I also would very much like to see the logic being implemented in the controller. This way one doesn't have to reply on every init system's reboot. Me for example hitting the same problem @dweomer describes using Alma8 and rke2.
