### ISSUE TITLE
No history of a updated plan

### ISSUE THREAD

**Issue by siredmar** [rancher/system-upgrade-controller#238]
**Is your feature request related to a problem? Please describe.**
The problem is, that i can not possibly know which plan was applied to the node in the past. I know, that nodes get labeled with the `latestHash` of succeeded plans. However, if i simply update the same plan, i'm losing this kind of history information.

**Describe the solution you'd like**
Maybe the controller can create events for that plan resource that state the `targeted nodes`, `latestHash` and `latestVersion`.

**Describe alternatives you've considered**
Another possible solution would be to introduce a new CRD that keeps track of revisions of succeeded plans, e.g. `planRevisions` storing  `targeted nodes`, `latestHash` and `latestVersion`.

**Additional context**
None, but i'm happy to share more context if needed.

**Comment by dweomer** [comment]
Original author here (but not employed with SUSE):

I've always thought that an event should be sufficient but never dug into how to make the wrangler library emit them. I imagine it wouldn't be too difficult and I have some time on my hands, I may take a stab at such.

As for a CRD, an idea complimentary with events that I've also thought about, it seems a bit too meta for the aims of this project, I think. I am open to being convinced otherwise, however, can you share more detail of your use case that has made evident this need from SUC?

**Comment by brandond** [comment]
Events generally roll off after a couple hours so they're not great from an audit perspective, but I guess they can at least be audited and logged somewhere.

**Comment by brandond** [comment]
Please take a look at the above-linked PR, let me know if you have any feedback.
