### ISSUE TITLE
Error: WithLatestTag(): invalid tag format (on rancher/k3s-upgrade)

### ISSUE THREAD

**Issue by huiser** [rancher/system-upgrade-controller#94]
**Version**
not using system-upgrade-controller binary, but applying manifest 0.6.1

**Platform/Architecture**
K3S v1.17.4+k3s1

**Describe the bug**
After applying server-plan:

time="2020-06-24T09:11:05Z" level=error msg="WithLatestTag(): invalid tag format (on rancher/k3s-upgrade)"
E0624 09:11:05.321244       1 controller.go:135] error syncing 'system-upgrade/server-plan': handler system-upgrade-controller: Get https://update.k3s.io/v1-release/channels/stable: x509: certificate signed by unknown authority, handler system-upgrade-controller: failed to create system-upgrade/apply-server-plan-on-dvkube007188.nl.novamedia.com-with- batch/v1, Kind=Job for system-upgrade-controller system-upgrade/server-plan: Job.batch "apply-server-plan-on-dvkube007188.nl.novamedia.com-with-" is invalid: [metadata.name: Invalid value: "apply-server-plan-on-dvkube007188.nl.novamedia.com-with-": a DNS-1123 subdomain must consist of lower case alphanumeric characters, '-' or '.', and must start and end with an alphanumeric character (e.g. 'example.com', regex used for validation is '[a-z0-9]([-a-z0-9]*[a-z0-9])?(\.[a-z0-9]([-a-z0-9]*[a-z0-9])?)*'), spec.template.labels: Invalid value: "apply-server-plan-on-dvkube007188.nl.novamedia.com-with-": a valid label must be an empty string or consist of alphanumeric characters, '-', '_' or '.', and must start and end with an alphanumeric character (e.g. 'MyValue',  or 'my_value',  or '12345', regex used for validation is '(([A-Za-z0-9][-A-Za-z0-9_.]*)?[A-Za-z0-9])?')], requeuing

**To Reproduce**
Create controller:
```
kubectl apply -f https://github.com/rancher/system-upgrade-controller/releases/download/v0.6.1/system-upgrade-controller.yaml
```

server-plan.yaml:
```apiVersion: upgrade.cattle.io/v1
kind: Plan
metadata:
  name: server-plan
  namespace: system-upgrade
spec:
  concurrency: 1
  cordon: true
  nodeSelector:
    matchExpressions:
    - key: node-role.kubernetes.io/master
      operator: In
      values:
      - "true"
  serviceAccountName: system-upgrade
  upgrade:
    image: rancher/k3s-upgrade
  channel: https://update.k3s.io/v1-release/channels/stable
```
Add plan:
```
kubectl apply -f server-plan.yaml
```

**Comment by dweomer** [comment]
> E0624 09:11:05.321244 1 controller.go:135] error syncing 'system-upgrade/server-plan': handler system-upgrade-controller: Get https://update.k3s.io/v1-release/channels/stable: **x509: certificate signed by unknown authority**

This is an indication that your root of trust does not include a signing certificate for the cert presented by `update.k3s.io`. Please note that by default the system-upgrade-controller deployment attempts to bind mount this from the host: https://github.com/rancher/system-upgrade-controller/blob/v0.6.1/manifests/system-upgrade-controller.yaml#L84-L93

If your system does not have `/etc/ssl` you will need to change that `hostPath` to another directory honored by the go runtime (see https://golang.org/src/crypto/x509/root_linux.go). If, however, that directory is present on your system then what is mostly likely the problem is an out-of-date root of trust. This can typically be updated by upgrading the `ca-certificates` package (or similar) for your distribution.
